version: "3.8"

services:
  frontend-dev:
    build:
      context: ./my-aduanku
      dockerfile: Dockerfile.dev
    container_name: aduanku-frontend-dev
    ports:
      - "5173:5173"
    volumes:
      - ./my-aduanku:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
    restart: unless-stopped
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge
