version: "3.8"

services:
  frontend:
    build: ./my-aduanku
    container_name: aduanku-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge
