version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    command: mongod --replSet rs0
    restart: unless-stopped

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - NODE_ENV=production
      - DB_URI=${AUTH_DB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=15m
    depends_on:
      - mongodb
    restart: unless-stopped

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "5002:5002"
    environment:
      - PORT=5002
      - NODE_ENV=production
      - DB_URI=${USER_DB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - S3_BUCKET=${S3_BUCKET}
    depends_on:
      - mongodb
    restart: unless-stopped

  issue-service:
    build: ./issue-service
    container_name: issue-service
    ports:
      - "5003:5003"
    environment:
      - PORT=5003
      - NODE_ENV=production
      - DB_URI=${ISSUE_DB_URI}
      - JWT_SECRET=${JWT_SECRET}
      # S3 (only if using uploads)
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - S3_BUCKET=${S3_BUCKET}
    depends_on:
      - mongodb
    restart: unless-stopped

  comments-service:
    build: ./comments-service
    container_name: comments-service
    ports:
      - "5004:5004"
    environment:
      - PORT=5004
      - NODE_ENV=production
      - DB_URI=${COMMENTS_DB_URI}
      - JWT_SECRET=${JWT_SECRET}
      # S3 (only if using uploads)
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - S3_BUCKET=${S3_BUCKET}
    depends_on:
      - mongodb
    restart: unless-stopped

  analytics-service:
    build: ./analytics-service
    container_name: analytics-service
    ports:
      - "5005:5005"
    environment:
      - PORT=5005
      - NODE_ENV=production
      - DB_URI=${ANALYTICS_DB_URI}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongodb
    restart: unless-stopped

volumes:
  mongodb_data: