version: "3.8"
services:
  analytics-service:
    build: .
    container_name: analytics-service
    ports:
      - "5005:5005"
    environment:
      - PORT=5005
      - NODE_ENV=production
      - DB_URI=${ANALYTICS_DB_URI}
      - JWT_SECRET=${JWT_SECRET}
    restart: unless-stopped