version: "3.8"
services:
  auth-service:
    build: .
    container_name: auth-service
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - NODE_ENV=production
      - DB_URI=${AUTH_DB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=15m
    restart: unless-stopped