version: "3.8"
services:
  user-service:
    build: .
    container_name: user-service
    ports:
      - "5002:5002"
    environment:
      - PORT=5002
      - NODE_ENV=production
      - DB_URI=${USER_DB_URI}
      - JWT_SECRET=${JWT_SECRET}
    restart: unless-stopped